#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

# Wait upto 30s for db to be ready
php artisan db:ready

if [ ! -d /.composer ]; then
    mkdir /.composer
    echo "Running Initial App Setup"
    php artisan app:setup --force
else
    echo "Running Minimal App Setup"
    php artisan app:setup
fi

chmod -R ugo+rw /.composer


if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
